# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kalibrate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NinjaAttack
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  
  #mopinion pods
  pod 'MopinionSDK',  '~> 0.4.4'
  pod 'React', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
  pod 'react-native-webview', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
  pod 'yoga', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
  pod 'DoubleConversion', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
  pod 'GLog', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
  pod 'Folly', :git => 'https://github.com/mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'
end
