# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kalibrate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NinjaAttack
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  
  #survey monkey
  pod 'surveymonkey-ios-sdk', '~> 2.0'
end
